-- Drop existing tables to reset schema
drop table if exists order_items;
drop table if exists orders;

-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  status text check (status in ('pending', 'processing', 'shipped', 'cancelled')) default 'pending',
  total_amount numeric(10, 2) not null,
  shipping_address text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create order_items table
-- Added user_id to simplify RLS policies
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  product_id bigint not null,
  product_name text not null,
  quantity int not null,
  price numeric(10, 2) not null
);

-- Enable RLS
alter table orders enable row level security;
alter table order_items enable row level security;

-- Policies for orders
create policy "Users can view own orders" on orders
  for select using (auth.uid() = user_id);

create policy "Users can create orders" on orders
  for insert with check (auth.uid() = user_id);

-- Policies for order_items
-- Now we can simply check the user_id on the item itself
create policy "Users can view own order items" on order_items
  for select using (auth.uid() = user_id);

create policy "Users can create order items" on order_items
  for insert with check (auth.uid() = user_id);
