/**
 * This file is auto-generated by scripts/manage-fonts.js
 * Do not edit manually.
 */

export interface FontDefinition {
    name: string;
    fileName: string;
    family: string;
}

export const AVAILABLE_FONTS: FontDefinition[] = [
    {
        "name": "Assistant-Bold",
        "fileName": "Assistant-Bold.woff2",
        "family": "Assistant"
    },
    {
        "name": "Assistant-Regular",
        "fileName": "Assistant-Regular.woff2",
        "family": "Assistant"
    },
    {
        "name": "Inter-Bold",
        "fileName": "Inter-Bold.woff2",
        "family": "Inter"
    },
    {
        "name": "Inter-Regular",
        "fileName": "Inter-Regular.woff2",
        "family": "Inter"
    },
    {
        "name": "OpenSans-Bold",
        "fileName": "OpenSans-Bold.woff2",
        "family": "Open Sans"
    },
    {
        "name": "OpenSans-Regular",
        "fileName": "OpenSans-Regular.woff2",
        "family": "Open Sans"
    },
    {
        "name": "PlayfairDisplay-Bold",
        "fileName": "PlayfairDisplay-Bold.woff2",
        "family": "Playfair Display"
    },
    {
        "name": "PlayfairDisplay-Regular",
        "fileName": "PlayfairDisplay-Regular.woff2",
        "family": "Playfair Display"
    },
    {
        "name": "Roboto-Bold",
        "fileName": "Roboto-Bold.woff2",
        "family": "Roboto"
    },
    {
        "name": "Roboto-Regular",
        "fileName": "Roboto-Regular.woff2",
        "family": "Roboto"
    }
];
