
import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const FONTS = [
	'Inter',
	'Roboto',
	'Open Sans',
	'Playfair Display',
	'Assistant'
];

const VARIANTS = [
	{ weight: '400', name: 'Regular' },
	{ weight: '700', name: 'Bold' }
];

const FONTS_DIR = path.join(__dirname, '../public/fonts');
const CONSTANTS_FILE = path.join(__dirname, '../src/constants/fonts.ts');

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36';

// Ensure fonts directory exists
if (!fs.existsSync(FONTS_DIR)) {
	fs.mkdirSync(FONTS_DIR, { recursive: true });
}

async function fetchContent(url) {
	return new Promise((resolve, reject) => {
		https.get(url, { headers: { 'User-Agent': USER_AGENT } }, (res) => {
			if (res.statusCode !== 200) {
				reject(new Error(`Request failed: ${res.statusCode}`));
				return;
			}
			let data = '';
			res.on('data', chunk => data += chunk);
			res.on('end', () => resolve(data));
		}).on('error', reject);
	});
}

async function downloadFile(url, dest) {
	return new Promise((resolve, reject) => {
		const file = fs.createWriteStream(dest);
		https.get(url, { headers: { 'User-Agent': USER_AGENT } }, (res) => {
			if (res.statusCode !== 200) {
				reject(new Error(`Download failed: ${res.statusCode}`));
				return;
			}
			res.pipe(file);
			file.on('finish', () => {
				file.close();
				resolve();
			});
		}).on('error', (err) => {
			fs.unlink(dest, () => { });
			reject(err);
		});
	});
}

async function setupFonts() {
	console.log('Managing Fonts...');

	// 1. Download missing fonts
	for (const font of FONTS) {
		for (const variant of VARIANTS) {
			const fileName = `${font.replace(/\s+/g, '')}-${variant.name}.woff2`;
			const destPath = path.join(FONTS_DIR, fileName);

			if (fs.existsSync(destPath)) {
				console.log(`✓ ${fileName} exists.`);
				continue;
			}

			console.log(`Processing ${font} (${variant.name})...`);

			try {
				// Fetch CSS
				const cssUrl = `https://fonts.googleapis.com/css2?family=${font.replace(/\s+/g, '+')}:wght@${variant.weight}`;
				const css = await fetchContent(cssUrl);

				// Extract URL (Try latin first, then fallback)
				let match = css.match(/\/\* latin \*\/[\s\S]*?src: url\(([^)]+)\)/);
				if (!match) {
					match = css.match(/src: url\(([^)]+)\)/);
				}

				if (match && match[1]) {
					const fontUrl = match[1];
					// console.log(`  Downloading from ${fontUrl}`);
					await downloadFile(fontUrl, destPath);
					console.log(`  Downloaded ${fileName}`);
				} else {
					console.error(`  Could not parse CSS for ${font}`);
				}
			} catch (err) {
				console.error(`  Error processing ${font}:`, err.message);
			}
		}
	}

	// 2. Generate Constants
	console.log('Generating font constants...');

	// Clean up non-font files? (optional, skipping for safety)

	const validExtensions = ['.ttf', '.otf', '.woff', '.woff2'];
	const fontFiles = fs.readdirSync(FONTS_DIR)
		.filter(file => validExtensions.includes(path.extname(file).toLowerCase()))
		.sort();

	const fontDefinitions = fontFiles.map(file => {
		const name = path.parse(file).name;
		// Guess family
		// "Inter-Bold" -> "Inter"
		// "OpenSans-Regular" -> "OpenSans" (Need to space it out?)
		// The script names them "OpenSans-Regular" etc.
		let family = name.split('-')[0];
		// Insert spaces before Capitals if needed
		family = family.replace(/([a-z])([A-Z])/g, '$1 $2');

		return {
			name: name,
			fileName: file,
			family: family
		};
	});

	const fileContent = `/**
 * This file is auto-generated by scripts/manage-fonts.js
 * Do not edit manually.
 */

export interface FontDefinition {
    name: string;
    fileName: string;
    family: string;
}

export const AVAILABLE_FONTS: FontDefinition[] = ${JSON.stringify(fontDefinitions, null, 4)};
`;

	// Ensure constants dir exists
	const constantsDir = path.dirname(CONSTANTS_FILE);
	if (!fs.existsSync(constantsDir)) {
		fs.mkdirSync(constantsDir, { recursive: true });
	}

	fs.writeFileSync(CONSTANTS_FILE, fileContent);
	console.log(`✓ Generated ${CONSTANTS_FILE} with ${fontDefinitions.length} fonts.`);
}

setupFonts().catch(err => {
	console.error(err);
	process.exit(1);
});
