


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."product_status" AS ENUM (
    'active',
    'inactive',
    'draft',
    'archived'
);


ALTER TYPE "public"."product_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_product_average_rating"("p_id" bigint) RETURNS numeric
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    RETURN (SELECT COALESCE(AVG(rating), 0) FROM public.reviews WHERE product_id = p_id);
END;
$$;


ALTER FUNCTION "public"."get_product_average_rating"("p_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_product_review_count"("p_id" bigint) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    RETURN (SELECT COUNT(*) FROM public.reviews WHERE product_id = p_id);
END;
$$;


ALTER FUNCTION "public"."get_product_review_count"("p_id" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_user_email_sync"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
begin
  insert into public.profiles (id, email, email_verified, full_name)
  values (
    new.id,
    new.email,
    (new.email_confirmed_at is not null),
    new.raw_user_meta_data->>'full_name'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    email_verified = excluded.email_verified,
    full_name = excluded.full_name;
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_user_email_sync"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_user_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_catalog'
    AS $$
begin
  update public.profiles
  set
    email = new.email,
    email_verified = (new.email_confirmed_at is not null),
    full_name = new.raw_user_meta_data->>'full_name'
  where id = new.id;
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_user_update"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1
    FROM profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_current_user_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_catalog'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = (SELECT auth.uid())
      AND role = 'admin'
  );
$$;


ALTER FUNCTION "public"."is_current_user_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_owner"("p_user_id" "uuid") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  SELECT (SELECT auth.uid()) = p_user_id;
$$;


ALTER FUNCTION "public"."is_owner"("p_user_id" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."addresses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "address_line1" "text" NOT NULL,
    "address_line2" "text",
    "city" "text" NOT NULL,
    "state" "text" NOT NULL,
    "zip_code" "text" NOT NULL,
    "country" "text" DEFAULT 'US'::"text",
    "is_default" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."addresses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."order_items" (
    "id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "product_id" bigint NOT NULL,
    "product_name" "text" NOT NULL,
    "quantity" integer NOT NULL,
    "price" numeric(10,2) NOT NULL
);


ALTER TABLE "public"."order_items" OWNER TO "postgres";


ALTER TABLE "public"."order_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."order_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text",
    "total_amount" numeric(10,2) NOT NULL,
    "shipping_address" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "orders_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'processing'::"text", 'shipped'::"text", 'cancelled'::"text"])))
);


ALTER TABLE "public"."orders" OWNER TO "postgres";


ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "price" numeric NOT NULL,
    "description" "text",
    "image" "text",
    "category" "text",
    "on_hand" integer DEFAULT 0,
    "images" "text"[] DEFAULT '{}'::"text"[],
    "cost" numeric,
    "sku" "text",
    "tags" "text"[] DEFAULT '{}'::"text"[],
    "weight" numeric,
    "product_type" "text",
    "brand" "text",
    "gtin" "text",
    "mpn" "text",
    "condition" "text" DEFAULT 'new'::"text",
    "status" "public"."product_status" DEFAULT 'draft'::"public"."product_status",
    "variant" "text"
);


ALTER TABLE "public"."products" OWNER TO "postgres";


ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'customer'::"text",
    "full_name" "text",
    "updated_at" timestamp with time zone,
    "phone_number" "text",
    "email" "text",
    "email_verified" boolean DEFAULT false,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['customer'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reviews" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "product_id" bigint NOT NULL,
    "order_id" bigint NOT NULL,
    "rating" integer NOT NULL,
    "comment" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "reviews_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5))),
    CONSTRAINT "reviews_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."reviews" OWNER TO "postgres";


ALTER TABLE "public"."reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."store_settings" (
    "id" integer DEFAULT 1 NOT NULL,
    "store_name" "text" DEFAULT 'Open E-Commerce'::"text" NOT NULL,
    "support_email" "text",
    "primary_color" "text" DEFAULT '#2563eb'::"text" NOT NULL,
    "secondary_color" "text" DEFAULT '#f8fafc'::"text" NOT NULL,
    "logo_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "colors_background_1" "text" DEFAULT '#FFFFFF'::"text",
    "colors_text" "text" DEFAULT '#121212'::"text",
    "colors_solid_button_labels" "text" DEFAULT '#FFFFFF'::"text",
    "colors_accent_1" "text" DEFAULT '#000000'::"text",
    "colors_accent_2" "text" DEFAULT '#334FB4'::"text",
    "gradient_background_1" "text",
    "type_header_font" "text" DEFAULT 'Assistant'::"text",
    "type_body_font" "text" DEFAULT 'Inter'::"text",
    "type_header_scale" integer DEFAULT 100,
    "type_body_scale" integer DEFAULT 100,
    "page_width" integer DEFAULT 1200,
    "spacing_grid_horizontal" integer DEFAULT 8,
    "spacing_grid_vertical" integer DEFAULT 8,
    "buttons_border_thickness" integer DEFAULT 1,
    "buttons_opacity" integer DEFAULT 100,
    "buttons_radius" integer DEFAULT 0,
    "buttons_shadow_opacity" integer DEFAULT 0,
    "buttons_shadow_horizontal_offset" integer DEFAULT 0,
    "image_ratio" "text" DEFAULT 'adapt'::"text",
    "show_secondary_image" boolean DEFAULT true,
    "show_brand" boolean DEFAULT false,
    "show_rating" boolean DEFAULT false,
    "enable_quick_add" boolean DEFAULT true,
    "social_facebook_link" "text" DEFAULT ''::"text",
    "social_instagram_link" "text" DEFAULT ''::"text",
    "social_youtube_link" "text" DEFAULT ''::"text",
    "social_tiktok_link" "text" DEFAULT ''::"text",
    "social_twitter_link" "text" DEFAULT ''::"text",
    "social_pinterest_link" "text" DEFAULT ''::"text",
    "social_snapchat_link" "text" DEFAULT ''::"text",
    "social_tumblr_link" "text" DEFAULT ''::"text",
    "social_vimeo_link" "text" DEFAULT ''::"text",
    "favicon_url" "text" DEFAULT ''::"text",
    "currency_code_enabled" boolean DEFAULT true,
    "cart_type" "text" DEFAULT 'drawer'::"text",
    "predictive_search_enabled" boolean DEFAULT true,
    "colors_background_light" "text" DEFAULT '#FFFFFF'::"text",
    "colors_background_dark" "text" DEFAULT '#09090b'::"text",
    "colors_text_light" "text" DEFAULT '#121212'::"text",
    "colors_text_dark" "text" DEFAULT '#f8fafc'::"text",
    "social_github_link" "text" DEFAULT ''::"text",
    CONSTRAINT "single_row" CHECK (("id" = 1))
);


ALTER TABLE "public"."store_settings" OWNER TO "postgres";


ALTER TABLE ONLY "public"."addresses"
    ADD CONSTRAINT "addresses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."store_settings"
    ADD CONSTRAINT "store_settings_pkey" PRIMARY KEY ("id");



CREATE INDEX "addresses_user_id_idx" ON "public"."addresses" USING "btree" ("user_id");



CREATE INDEX "idx_order_items_order_id" ON "public"."order_items" USING "btree" ("order_id");



CREATE INDEX "idx_order_items_product_id" ON "public"."order_items" USING "btree" ("product_id");



CREATE INDEX "idx_order_items_user_id" ON "public"."order_items" USING "btree" ("user_id");



CREATE INDEX "idx_orders_user_id" ON "public"."orders" USING "btree" ("user_id");



CREATE INDEX "idx_products_status" ON "public"."products" USING "btree" ("status");



CREATE INDEX "products_brand_idx" ON "public"."products" USING "btree" ("brand");



CREATE INDEX "products_gtin_idx" ON "public"."products" USING "btree" ("gtin");



CREATE INDEX "products_sku_idx" ON "public"."products" USING "btree" ("sku");



ALTER TABLE ONLY "public"."addresses"
    ADD CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."order_items"
    ADD CONSTRAINT "order_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;



CREATE POLICY "Admins can update reviews" ON "public"."reviews" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text")))));



CREATE POLICY "Admins can view all reviews" ON "public"."reviews" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text")))));



CREATE POLICY "Allow admins to update settings" ON "public"."store_settings" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles"
  WHERE (("profiles"."id" = "auth"."uid"()) AND ("profiles"."role" = 'admin'::"text")))));



CREATE POLICY "Allow public read access" ON "public"."products" FOR SELECT USING (true);



CREATE POLICY "Allow public read access" ON "public"."store_settings" FOR SELECT USING (true);



CREATE POLICY "Authenticated users can insert reviews" ON "public"."reviews" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Public can view approved reviews" ON "public"."reviews" FOR SELECT USING (("status" = 'approved'::"text"));



CREATE POLICY "Users can delete their own reviews" ON "public"."reviews" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view their own reviews" ON "public"."reviews" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."addresses" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "addresses_access_policy" ON "public"."addresses" TO "authenticated" USING ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false))) WITH CHECK ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false)));



ALTER TABLE "public"."order_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "order_items_access_policy" ON "public"."order_items" TO "authenticated" USING ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false))) WITH CHECK ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false)));



ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "orders_access_policy" ON "public"."orders" TO "authenticated" USING ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false))) WITH CHECK ((COALESCE("public"."is_owner"("user_id"), false) OR COALESCE("public"."is_admin"(), false)));



ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "products_admin_only_delete" ON "public"."products" FOR DELETE TO "authenticated" USING (COALESCE("public"."is_admin"(), false));



CREATE POLICY "products_admin_only_insert" ON "public"."products" FOR INSERT TO "authenticated" WITH CHECK (COALESCE("public"."is_admin"(), false));



CREATE POLICY "products_admin_only_update" ON "public"."products" FOR UPDATE TO "authenticated" USING (COALESCE("public"."is_admin"(), false)) WITH CHECK (COALESCE("public"."is_admin"(), false));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_access_policy" ON "public"."profiles" TO "authenticated" USING ((COALESCE("public"."is_owner"("id"), false) OR COALESCE("public"."is_admin"(), false))) WITH CHECK ((COALESCE("public"."is_owner"("id"), false) OR COALESCE("public"."is_admin"(), false)));



ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."store_settings" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."store_settings";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."get_product_average_rating"("p_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."get_product_average_rating"("p_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_product_average_rating"("p_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_product_review_count"("p_id" bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."get_product_review_count"("p_id" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_product_review_count"("p_id" bigint) TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_user_email_sync"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_user_email_sync"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_user_email_sync"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_user_update"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_user_update"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_user_update"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_current_user_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_owner"("p_user_id" "uuid") TO "service_role";


















GRANT ALL ON TABLE "public"."addresses" TO "anon";
GRANT ALL ON TABLE "public"."addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."addresses" TO "service_role";



GRANT ALL ON TABLE "public"."order_items" TO "anon";
GRANT ALL ON TABLE "public"."order_items" TO "authenticated";
GRANT ALL ON TABLE "public"."order_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."order_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";



GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."reviews" TO "anon";
GRANT ALL ON TABLE "public"."reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."store_settings" TO "anon";
GRANT ALL ON TABLE "public"."store_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."store_settings" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created_email_sync AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_user_email_sync();

CREATE TRIGGER on_auth_user_updated AFTER UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_user_update();


